server:
  port: 8200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: service-consumer

spring:
  application:
    name: service-consumer
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
